/**
 * Beckn Core API
 * Beckn Core API specification
 *
 * OpenAPI spec version: 0.9.1-draft03
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.beckn.one.sandbox.bap.dtos

data class Category(
    val id: String? = null,
    val children: List<String> = emptyList(),
    val parentId: String? = null,
    val descriptor: Descriptor? = null
)